[package]
name = "dora-runtime"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
dora-node-api = { path = "../../apis/rust/node", default-features = false, features = [
    "zenoh",
    "iceoryx",
] }
dora-operator-api-python = { path = "../../apis/python/operator" }
dora-operator-api-types = { path = "../../apis/rust/operator/types" }
dora-core = { workspace = true }
dora-tracing = { path = "../../libraries/extensions/telemetry/tracing", optional = true }
dora-metrics = { path = "../../libraries/extensions/telemetry/metrics", optional = true }
opentelemetry = { version = "0.17", features = [
    "rt-tokio",
    "metrics",
], optional = true }
opentelemetry-system-metrics = { version = "0.1.1", optional = true }
eyre = "0.6.8"
futures = "0.3.21"
futures-concurrency = "2.0.3"
libloading = "0.7.3"
serde_yaml = "0.8.23"
tokio = { version = "1.23.1", features = ["full"] }
tokio-stream = "0.1.8"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", rev = "79a136e4fd90b11ff5d775ced981af53c4f1071b" }
zenoh-config = { git = "https://github.com/eclipse-zenoh/zenoh.git", rev = "79a136e4fd90b11ff5d775ced981af53c4f1071b" }
fern = "0.6.1"
pyo3 = { version = "0.18", features = ["eyre", "abi3-py37"] }
# pyo3-abi3 flag allow simpler linking. See: https://pyo3.rs/v0.13.2/building_and_distribution.html
flume = "0.10.14"
dora-message = { path = "../../libraries/message" }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
dora-download = { path = "../../libraries/extensions/download" }

[features]
tracing = ["opentelemetry", "dora-tracing"]
metrics = ["opentelemetry", "opentelemetry-system-metrics", "dora-metrics"]
